import{a as l,S as y,i as g}from"./assets/vendor-59537f4e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();l.defaults.headers.common["x-api-key"]="live_zOF9vaVYvRLCPyKToIzWhj09cqgYYpxHWkm34YngZLYhyG9MTetGTjwduOAth2Cz";const f="Oops! Something went wrong! Try realoding the page!",m="https://api.thecatapi.com/v1";async function L(){try{return(await l.get(`${m}/breeds`)).data}catch{throw new Error(f)}}async function v(e){try{return(await l.get(`${m}/images/search?breed_ids=${e}`)).data}catch{throw new Error(f)}}const c=document.getElementById("breed-select"),a=document.querySelector(".loader"),i=document.querySelector(".cat-info"),u=document.querySelector(".error");async function w(){a.classList.remove("hidden"),c.classList.add("hidden");try{const e=await L();e.forEach(t=>{const s=document.createElement("option");s.value=t.id,s.textContent=t.name,c.appendChild(s)}),new y({select:"#breed-select"}),c.classList.remove("hidden"),e.length>0&&h(e[0].id)}catch(e){p(e.message)}finally{a.classList.add("hidden")}}async function h(e){a.classList.remove("hidden"),i.classList.add("hidden");try{i.classList.add("hidden");const[t]=await v(e);b(t)}catch(t){p(t.message)}finally{a.classList.add("hidden")}}function b(e){const{url:t,breeds:s}=e,n=s[0];i.innerHTML=`
          <img src="${t}" alt="${n.name}">
          <div class="cat-info-text">
              <h2>${n.name}</h2>
              <p>${n.description}</p>
              <p><strong>Temperament:</strong> ${n.temperament}</p>
          </div>
      `,i.classList.remove("hidden")}function p(e){u.textContent=e,u.classList.remove("hidden"),g.error({title:"Error",message:e})}document.addEventListener("DOMContentLoaded",()=>{w()});c.addEventListener("change",e=>{const t=e.target.value;console.log(e),t&&h(t)});
//# sourceMappingURL=commonHelpers.js.map
