import{a as f,S as y,i as g}from"./assets/vendor-59537f4e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();f.defaults.headers.common["x-api-key"]="live_zOF9vaVYvRLCPyKToIzWhj09cqgYYpxHWkm34YngZLYhyG9MTetGTjwduOAth2Cz";const h="Oops! Something went wrong! Try realoding the page!",m="https://api.thecatapi.com/v1";async function L(){try{return(await f.get(`${m}/breeds`)).data}catch{throw new Error(h)}}async function v(e){try{return(await f.get(`${m}/images/search?breed_ids=${e}`)).data}catch{throw new Error(h)}}const c=document.getElementById("breed-select"),a=document.querySelector(".loader"),i=document.querySelector(".cat-info"),l=document.querySelector(".error");async function w(){a.classList.remove("hidden"),c.classList.add("hidden");try{const e=await L();e.forEach(t=>{const n=document.createElement("option");n.value=t.id,n.textContent=t.name,c.appendChild(n)}),new y({select:"#breed-select"}),c.classList.remove("hidden"),e.length>0&&p(e[0].id)}catch(e){u(e.message)}finally{a.classList.add("hidden")}}async function p(e){a.classList.remove("hidden"),i.classList.add("hidden"),l.classList.add("hidden");try{i.classList.add("hidden");const[t]=await v(e);E(t)}catch(t){u(t.message)}finally{a.classList.add("hidden")}}function E(e){try{var{url:t,breeds:n}=e,s=n[0];i.innerHTML=`
          <img src="${t}" alt="${s.name}">
          <div class="cat-info-text">
              <h2>${s.name}</h2>
              <p>${s.description}</p>
              <p><strong>Temperament:</strong> ${s.temperament}</p>
          </div>
      `,i.classList.remove("hidden")}catch(r){u("We cannot find information on this breed. Please check other breeds!"),console.log(r)}}function u(e){l.textContent=e,l.classList.remove("hidden"),g.error({title:"Error",message:e})}document.addEventListener("DOMContentLoaded",()=>{w()});c.addEventListener("change",e=>{const t=e.target.value;t&&p(t)});
//# sourceMappingURL=commonHelpers.js.map
