import{a as l,S as p,i as y}from"./assets/vendor-59537f4e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();l.defaults.headers.common["x-api-key"]="live_zOF9vaVYvRLCPyKToIzWhj09cqgYYpxHWkm34YngZLYhyG9MTetGTjwduOAth2Cz";const h="Oops! Something went wrong! Try realoding the page!",m="https://api.thecatapi.com/v1";async function g(){try{return(await l.get(`${m}/breeds`)).data}catch{throw new Error(h)}}async function L(r){try{return(await l.get(`${m}/images/search?breed_ids=${r}`)).data}catch{throw new Error(h)}}const f=document.getElementById("breed-select"),a=document.querySelector(".loader"),c=document.querySelector(".cat-info"),d=document.querySelector(".error");async function v(){a.classList.remove("hidden"),f.classList.add("hidden");try{var r=(await g()).map(({id:n,name:o})=>({text:o,value:n}));new p({select:"#breed-select",data:[{placeholder:!0,text:"Select breed"},...r],events:{afterChange:S}}),f.classList.remove("hidden")}catch(e){u(e.message)}finally{a.classList.add("hidden")}}async function w(r){a.classList.remove("hidden"),c.classList.add("hidden"),d.classList.add("hidden");try{c.classList.add("hidden");const[e]=await L(r);b(e)}catch(e){u(e.message)}finally{a.classList.add("hidden")}}function b(r){try{var{url:e,breeds:n}=r,o=n[0];c.innerHTML=`
          <img src="${e}" alt="${o.name}">
          <div class="cat-info-text">
              <h2>${o.name}</h2>
              <p>${o.description}</p>
              <p><strong>Temperament:</strong> ${o.temperament}</p>
          </div>
      `,c.classList.remove("hidden")}catch(t){u("We cannot find information on this breed. Please check other breeds!"),console.log(t)}}function u(r){d.textContent=r,d.classList.remove("hidden"),y.error({title:"Error",message:r})}document.addEventListener("DOMContentLoaded",()=>{v()});const S=r=>{const e=r[0].value;e&&w(e)};
//# sourceMappingURL=commonHelpers.js.map
